apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemoapp
spec:
  selector:
    matchLabels:
      app: mydemoapp
  replicas: 2
  template:
    metadata:
      labels:
        app: mydemoapp
    spec:
      containers:
      - name: mydemoapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
